name: CI

on:
  push:
    branches:
    - main
    - next
    paths-ignore:
    - '**.md*'
  pull_request:
    branches:
    - main
    - next
    paths-ignore:
    - '**.md*'

jobs:
  ci:
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - 'lint'
          - 'test'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Run lint
        run: yarn && yarn build && yarn ${{ matrix.command }}
        env:
          CI: true